version: '3'

services:
  db:
    container_name: clinic-db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pswd
      MYSQL_USER: foo
      MYSQL_PASSWORD: foo
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    healthcheck:
      test:  ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - clinic

  backend:
    container_name: clinic-backend
    image: moscicky/clinic-backend
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - db
    networks:
      - clinic

networks:
  clinic:
    driver: bridge