version: '3'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pswd
    ports:
      - 33061:3306
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:3306"]
#      interval: 30s
#      timeout: 10s
#      retries: 5

#  backend:
#    image: moscicky/clinic-backend
#    ports:
#      - 8080:8080
#    depends_on:
#      - "db"
#    restart: on-failure
#    links:
#      - "db"

